import { Destination, TravelGroup, VendorOffer, NotificationItem, UserProfile, Trip } from '../types';

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'araku-valley',
    name: 'Araku Valley',
    state: 'Andhra Pradesh',
    tagline: 'Misty hills, coffee plantations & ancient caves',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    description: 'A serene hill station in the Eastern Ghats renowned for lush green valleys, aromatic coffee plantations, breathtaking waterfalls, and the magnificent subterranean Borra Caves.',
    baseCost: 3800,
    bestTime: 'October to March',
    travelInfo: {
      nearestStation: 'Araku Railway Station (Vistadome train route)',
      nearestAirport: 'Visakhapatnam International (115 km)',
      localTransportModes: 'Shared Jeeps, Tempo Travelers, Private Cabs',
      weather: 'Pleasant 16°C – 24°C in October',
    },
    popularAttractions: [
      {
        name: 'Borra Caves',
        tag: 'Geological Wonder',
        description: 'Millions of years old million-stalactite limestone caves illuminated with dramatic multi-color spotlights.',
        estimatedSoloCost: 300,
        estimatedGroupCost: 200,
      },
      {
        name: 'Katiki Waterfalls',
        tag: 'Nature & Trekking',
        description: 'Perennial cascades through deep foliage reachable by an adventurous shared 4x4 safari drive.',
        estimatedSoloCost: 350,
        estimatedGroupCost: 220,
      },
      {
        name: 'Coffee Museum',
        tag: 'Heritage & Tasting',
        description: 'Explore the origin of Araku organic tribal coffee with guided bean roasting and tasting sessions.',
        estimatedSoloCost: 150,
        estimatedGroupCost: 100,
      },
      {
        name: 'Tribal Museum',
        tag: 'Culture',
        description: 'Vibrant display of local indigenous lifestyle, handmade handicrafts, archery, and tribal dances.',
        estimatedSoloCost: 100,
        estimatedGroupCost: 60,
      },
      {
        name: 'Padmapuram Gardens',
        tag: 'Botanical Park',
        description: 'Historic horticulture garden featuring tree-top hanging cottages, exotic flowers, and a toy train.',
        estimatedSoloCost: 120,
        estimatedGroupCost: 70,
      },
    ],
    partnerOffersCount: 8,
    mapPoints: [
      { id: 'm1', name: 'Borra Caves Entrance', category: 'attraction', description: 'Ancient limestone cavern complex', discountNote: 'Group fast-track 33% off', x: 28, y: 35, rating: 4.8 },
      { id: 'm2', name: 'Katiki Falls Base Camp', category: 'attraction', description: 'Waterfall jeep assembly point', discountNote: 'Shared 4x4 tempo discount', x: 68, y: 24, rating: 4.7 },
      { id: 'm3', name: 'Haritha Valley Resort', category: 'hotel', description: 'Premium group cottages & lawn', discountNote: '₹450/person group tariff rebate', x: 45, y: 52, rating: 4.6 },
      { id: 'm4', name: 'Araku Coffee House & Dining', category: 'restaurant', description: 'Local tribal thali & filter coffee', discountNote: 'Group feast discount 20%', x: 50, y: 44, rating: 4.5 },
      { id: 'm5', name: 'Araku Junction Hub', category: 'meeting', description: 'Primary bus & shared tempo meeting point', discountNote: 'Boarding point for TERRA VISTAS groups', x: 38, y: 65, rating: 4.9 },
      { id: 'm6', name: 'Padmapuram Botanical Park', category: 'attraction', description: 'Historic floral gardens', discountNote: 'Combo group ticket', x: 58, y: 60, rating: 4.4 },
    ],
  },
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    tagline: 'City of Destiny - Coastal cliffs & submarine heritage',
    image: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=1200&q=80',
    description: 'A coastal metropolis offering clean sandy beaches, historic naval submarine museum, dolphin-shaped hillocks, and ropeways overlooking the Bay of Bengal.',
    baseCost: 4200,
    bestTime: 'September to March',
    travelInfo: {
      nearestStation: 'Visakhapatnam Junction (City Center)',
      nearestAirport: 'Visakhapatnam International (VTZ)',
      localTransportModes: 'Auto-rickshaws, city buses, AC tourist vans',
      weather: 'Coastal breeze, 23°C – 29°C',
    },
    popularAttractions: [
      { name: 'RK Beach & Promenade', tag: 'Coastline', description: 'Bustling beach road with food stalls and sea views', estimatedSoloCost: 100, estimatedGroupCost: 50 },
      { name: 'INS Kursura Submarine Museum', tag: 'Naval Heritage', description: 'Historic Soviet-built Russian submarine on real beach sand', estimatedSoloCost: 150, estimatedGroupCost: 100 },
      { name: 'Kailasagiri Hilltop Park', tag: 'Scenic Viewpoint', description: 'Panoramic cliff views reachable by ropeway cable car', estimatedSoloCost: 200, estimatedGroupCost: 130 },
      { name: 'Yarada Beach', tag: 'Secluded Beach', description: 'Golden sands enclosed by hills on three sides', estimatedSoloCost: 300, estimatedGroupCost: 180 },
      { name: "Dolphin's Nose Lighthouse", tag: 'Landmark', description: 'Historic 174m high headland overlooking the harbor', estimatedSoloCost: 150, estimatedGroupCost: 90 },
    ],
    partnerOffersCount: 12,
    mapPoints: [
      { id: 'v1', name: 'INS Kursura Submarine', category: 'attraction', description: 'Beachfront decommissioned submarine', discountNote: 'Group entry discount 25%', x: 62, y: 55, rating: 4.9 },
      { id: 'v2', name: 'Kailasagiri Ropeway Base', category: 'attraction', description: 'Hilltop cable car station', discountNote: 'Bulk cable car token pass', x: 45, y: 30, rating: 4.7 },
      { id: 'v3', name: 'Bay View Beach Hotel', category: 'hotel', description: 'Sea-facing rooms with breakfast', discountNote: 'Group tariff 30% saving', x: 55, y: 62, rating: 4.5 },
      { id: 'v4', name: 'Dolphin Harbor Meeting Point', category: 'meeting', description: 'Central tourist congregation zone', discountNote: 'Shared AC coaster departure', x: 35, y: 70, rating: 4.8 },
      { id: 'v5', name: 'Sea Inn Coastal Kitchen', category: 'restaurant', description: 'Fresh seafood & Andhra delicacies', discountNote: 'Fixed group banquet rate', x: 68, y: 48, rating: 4.6 },
    ],
  },
  {
    id: 'goa',
    name: 'Goa',
    state: 'Goa',
    tagline: 'Sun-drenched shores, Portuguese architecture & watersports',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    description: 'India’s ultimate coastal paradise known for vibrant beach shacks, historic UNESCO churches, spice plantations, and shared catamaran excursions.',
    baseCost: 5500,
    bestTime: 'October to April',
    travelInfo: {
      nearestStation: 'Madgaon (MAO) / Thivim (THVM)',
      nearestAirport: 'Dabolim (GOI) / Manohar Mopa (GOX)',
      localTransportModes: 'Shared AC Mini-coaches, rental cruisers',
      weather: 'Tropical, sunny 24°C – 31°C',
    },
    popularAttractions: [
      { name: 'Calangute & Baga Coast', tag: 'Beach & Sports', description: 'Watersports, parasailing and beachside dining', estimatedSoloCost: 900, estimatedGroupCost: 550 },
      { name: 'Fort Aguada & Lighthouse', tag: '17th Century Fort', description: 'Portuguese coastal fortress overlooking Arabian Sea', estimatedSoloCost: 200, estimatedGroupCost: 120 },
      { name: 'Dudhsagar Waterfalls', tag: 'Nature Wonder', description: 'Four-tiered sea of milk cascade inside Bhagwan Mahaveer Sanctuary', estimatedSoloCost: 1200, estimatedGroupCost: 750 },
      { name: 'Old Goa Basilica of Bom Jesus', tag: 'UNESCO Heritage', description: 'Baroque architecture preserving relics of St. Francis Xavier', estimatedSoloCost: 100, estimatedGroupCost: 50 },
      { name: 'Mandovi Sunset River Cruise', tag: 'Cultural Cruise', description: 'Goan folk dances and DJ cruise over the calm river', estimatedSoloCost: 600, estimatedGroupCost: 380 },
    ],
    partnerOffersCount: 19,
    mapPoints: [
      { id: 'g1', name: 'Fort Aguada Ramparts', category: 'attraction', description: 'Oceanfront historic defense walls', discountNote: 'Group entry & guide included', x: 25, y: 38, rating: 4.8 },
      { id: 'g2', name: 'Calangute Central Pier', category: 'meeting', description: 'TERRA VISTAS group watersports meet point', discountNote: 'Bulk parasailing packages', x: 38, y: 30, rating: 4.7 },
      { id: 'g3', name: 'Palm Grove Beach Resort', category: 'hotel', description: 'Boutique cottages with pool', discountNote: 'Group rate ₹1,200 vs ₹1,900', x: 42, y: 48, rating: 4.6 },
      { id: 'g4', name: 'Fisherman’s Wharf Dining', category: 'restaurant', description: 'Traditional Goan curry banquets', discountNote: 'Group set menu ₹450', x: 55, y: 65, rating: 4.8 },
      { id: 'g5', name: 'Mandovi River Jetty', category: 'attraction', description: 'Evening sunset cruise boarding', discountNote: 'Group charter deck save 35%', x: 60, y: 40, rating: 4.5 },
    ],
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    tagline: 'City of Pearls - Royal forts, Nizami cuisine & high-tech charm',
    image: 'https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=1200&q=80',
    description: 'Where 400-year-old Nizami history meets modern tech hubs. Famous for aromatic Dum Biryani, Golconda sound-and-light spectacles, and Ramoji Film City tours.',
    baseCost: 3900,
    bestTime: 'October to February',
    travelInfo: {
      nearestStation: 'Secunderabad / Hyderabad Deccan',
      nearestAirport: 'Rajiv Gandhi International (HYD)',
      localTransportModes: 'Metro Rail, AC Electric City Buses, Tempo',
      weather: 'Mild winters, 20°C – 28°C',
    },
    popularAttractions: [
      { name: 'Charminar & Laad Bazaar', tag: 'Iconic Monument', description: '1591 CE four-minaret monument with bangle bazaars', estimatedSoloCost: 150, estimatedGroupCost: 80 },
      { name: 'Golconda Fort Acoustic Tour', tag: 'Fortress', description: 'Engineering masterpiece known for claps heard 1 km away at Bala Hissar', estimatedSoloCost: 350, estimatedGroupCost: 200 },
      { name: 'Ramoji Film City', tag: 'Cinema Theme Park', description: 'World largest film studio complex with sets and live stunt shows', estimatedSoloCost: 1400, estimatedGroupCost: 950 },
      { name: 'Hussain Sagar & Buddha Statue', tag: 'Lakeside', description: 'Speedboat cruise to monolithic granite Buddha statue in lake', estimatedSoloCost: 250, estimatedGroupCost: 150 },
      { name: 'Salar Jung Museum', tag: 'Art Treasury', description: 'One of the three National Museums of India with clock room', estimatedSoloCost: 200, estimatedGroupCost: 120 },
    ],
    partnerOffersCount: 15,
    mapPoints: [
      { id: 'h1', name: 'Charminar Heritage Plazza', category: 'attraction', description: 'Four Minarets historic gate', discountNote: 'Walking tour group discount', x: 48, y: 72, rating: 4.8 },
      { id: 'h2', name: 'Golconda Fort Gate', category: 'attraction', description: 'Acoustic fort citadel', discountNote: 'Group sound & light show pass', x: 22, y: 55, rating: 4.9 },
      { id: 'h3', name: 'Paradise Nizami Kitchen', category: 'restaurant', description: 'World-famous authentic Hyderabadi Dum Biryani', discountNote: 'Group feast table discount', x: 52, y: 35, rating: 4.6 },
      { id: 'h4', name: 'Lakeside Transit Hub', category: 'meeting', description: 'Tank Bund TERRA VISTAS travelers meetup', discountNote: 'Central AC coach point', x: 49, y: 46, rating: 4.7 },
      { id: 'h5', name: 'Royal Residency Hotel', category: 'hotel', description: 'Comfortable centrally located rooms', discountNote: 'Group package ₹950/person', x: 62, y: 42, rating: 4.4 },
    ],
  },
  {
    id: 'tirupati',
    name: 'Tirupati',
    state: 'Andhra Pradesh',
    tagline: 'Spiritual heart of South India & sacred Seshachalam Hills',
    image: 'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=1200&q=80',
    description: 'Home to the ancient Sri Venkateswara Temple nestled among seven sacred peaks, with lush waterfalls, archaeological marvels, and peaceful foothill gardens.',
    baseCost: 3200,
    bestTime: 'September to March',
    travelInfo: {
      nearestStation: 'Tirupati Main (TPTY) / Renigunta (RU)',
      nearestAirport: 'Tirupati International (TIR)',
      localTransportModes: 'APSRTC Special Ghat Coaches, Shared Tempos',
      weather: 'Pleasant 21°C – 29°C',
    },
    popularAttractions: [
      { name: 'Tirumala Seshachalam Hills', tag: 'Sacred Heights', description: 'Seven scenic hill peaks with winding ghat roads', estimatedSoloCost: 300, estimatedGroupCost: 180 },
      { name: 'Kapila Theertham Falls', tag: 'Sacred Waterfall', description: 'Perennial waterfall cascading into a sacred temple tank', estimatedSoloCost: 80, estimatedGroupCost: 40 },
      { name: 'Chandragiri Fort & Palace', tag: 'Vijayanagara Heritage', description: '11th-century fort palace of Vijayanagara emperors with Raja Mahal', estimatedSoloCost: 150, estimatedGroupCost: 90 },
      { name: 'Silathoranam Natural Arch', tag: 'Natural Arch', description: 'Rare pre-Cambrian geological arch found in only two other spots globally', estimatedSoloCost: 100, estimatedGroupCost: 60 },
      { name: 'Sri Venkateswara Zoological Park', tag: 'Wildlife Reserve', description: 'Sprawling zoo set against natural hill forest backdrop', estimatedSoloCost: 120, estimatedGroupCost: 75 },
    ],
    partnerOffersCount: 9,
    mapPoints: [
      { id: 't1', name: 'Alipiri Foothill Meeting Hub', category: 'meeting', description: 'Main congregation & boarding station for uphill groups', discountNote: 'Dedicated group bus parking', x: 35, y: 65, rating: 4.9 },
      { id: 't2', name: 'Chandragiri Royal Palace', category: 'attraction', description: 'Vijayanagara fort ramparts', discountNote: 'Group heritage pass 30% off', x: 18, y: 78, rating: 4.6 },
      { id: 't3', name: 'Kapila Waterfall Sanctuary', category: 'attraction', description: 'Scenic rocky cascades', discountNote: 'Free pilgrim group facilitation', x: 50, y: 48, rating: 4.7 },
      { id: 't4', name: 'Srinivasa Pilgrim Residency', category: 'hotel', description: 'Hygienic AC family rooms', discountNote: 'Group discount ₹800 vs ₹1,300', x: 42, y: 58, rating: 4.5 },
      { id: 't5', name: 'Bhimas Traditional Kitchen', category: 'restaurant', description: 'Authentic South Indian vegetarian banana leaf meals', discountNote: 'Special group thali rate', x: 45, y: 62, rating: 4.8 },
    ],
  },
  {
    id: 'ooty',
    name: 'Ooty',
    state: 'Tamil Nadu',
    tagline: 'Queen of Hill Stations - Nilgiri toy train & tea slopes',
    image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    description: 'Nestled in the blue Nilgiri Mountains, featuring the historic steam railway, vast botanical terraces, emerald lakes, and pine forests shrouded in mist.',
    baseCost: 4400,
    bestTime: 'October to June',
    travelInfo: {
      nearestStation: 'Udhagamandalam / Mettupalayam',
      nearestAirport: 'Coimbatore International (88 km)',
      localTransportModes: 'Shared Minibuses, Mountain Tempos',
      weather: 'Crisp mountain air, 12°C – 20°C',
    },
    popularAttractions: [
      { name: 'Government Botanical Gardens', tag: 'Floral Terraces', description: 'Vast terraced slopes with over a thousand indigenous and exotic plants', estimatedSoloCost: 100, estimatedGroupCost: 60 },
      { name: 'Ooty Lake Boating', tag: 'Lakeside Fun', description: 'Serene artificial lake with pedal boats and eucalyptus trees', estimatedSoloCost: 350, estimatedGroupCost: 220 },
      { name: 'Nilgiri Mountain Railway', tag: 'UNESCO Toy Train', description: 'Century-old rack-and-pinion steam train ascending steep cliffs', estimatedSoloCost: 400, estimatedGroupCost: 260 },
      { name: 'Doddabetta Peak Viewpoint', tag: 'Highest Peak', description: 'Telescope house offering 360-degree vistas of the Western Ghats', estimatedSoloCost: 150, estimatedGroupCost: 90 },
      { name: 'Pykara Waterfalls & Lake', tag: 'Pristine Nature', description: 'Cascading river through shola forests with group speedboat rides', estimatedSoloCost: 450, estimatedGroupCost: 280 },
    ],
    partnerOffersCount: 14,
    mapPoints: [
      { id: 'o1', name: 'Botanical Garden Main Plaza', category: 'attraction', description: 'Terraced lawns & fossil tree', discountNote: 'Group ticketing counter', x: 55, y: 40, rating: 4.7 },
      { id: 'o2', name: 'Ooty Boathouse Hub', category: 'meeting', description: 'Lakeside boardwalk assembly point', discountNote: 'Group pontoon boat save 30%', x: 30, y: 55, rating: 4.8 },
      { id: 'o3', name: 'Nilgiri Mountain Steam Station', category: 'attraction', description: 'UNESCO heritage rail terminus', discountNote: 'Group reservations support', x: 42, y: 60, rating: 4.9 },
      { id: 'o4', name: 'Pine View Hilltop Resort', category: 'hotel', description: 'Heated cottage rooms with fire pits', discountNote: 'Group tariff ₹1,100/person', x: 65, y: 32, rating: 4.6 },
      { id: 'o5', name: 'Earl’s Secret Dining', category: 'restaurant', description: 'Colonial fireplace cafe & bakery', discountNote: 'Group high-tea discount 25%', x: 48, y: 45, rating: 4.5 },
    ],
  },
  {
    id: 'munnar',
    name: 'Munnar',
    state: 'Kerala',
    tagline: 'God’s Own Hill Station - Endless tea rolling hills & clouds',
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    description: 'Sprawling emerald tea estates perched at 1,600 meters where wild Nilgiri Tahrs roam, waterfalls cascade by the road, and spice gardens perfume the mountain breeze.',
    baseCost: 4600,
    bestTime: 'September to March',
    travelInfo: {
      nearestStation: 'Aluva / Ernakulam (120 km)',
      nearestAirport: 'Cochin International (110 km)',
      localTransportModes: 'Shared 4x4 Jeeps, Force Traveler vans',
      weather: 'Cool and misty, 13°C – 22°C',
    },
    popularAttractions: [
      { name: 'Tata Tea Museum & Factory', tag: 'Tea Processing', description: 'Watch live tea plucking, CTC processing, and vintage rollers in action', estimatedSoloCost: 200, estimatedGroupCost: 120 },
      { name: 'Eravikulam National Park', tag: 'Wildlife & Nilgiri Tahr', description: 'Sanctuary for the endangered mountain goat and Neelakurinji blooms', estimatedSoloCost: 450, estimatedGroupCost: 300 },
      { name: 'Mattupetty Dam & Lake', tag: 'Water & Hills', description: 'Concrete gravity dam with speedboating and reflection views', estimatedSoloCost: 350, estimatedGroupCost: 210 },
      { name: 'Anamudi Peak Base Trek', tag: 'Highest South Peak', description: 'View South India’s highest peak rising to 2,695 meters', estimatedSoloCost: 250, estimatedGroupCost: 150 },
      { name: 'Attukal Waterfalls', tag: 'Gushing Streams', description: 'Dramatic cascade between steep hills and wooden footbridges', estimatedSoloCost: 150, estimatedGroupCost: 80 },
    ],
    partnerOffersCount: 16,
    mapPoints: [
      { id: 'u1', name: 'Eravikulam Safari Gate', category: 'attraction', description: 'Eco-bus national park entrance', discountNote: 'Group bus reservation pass', x: 38, y: 22, rating: 4.9 },
      { id: 'u2', name: 'Mattupetty Dam Jetty', category: 'attraction', description: 'Speedboat cruise dock', discountNote: 'Group motorboat tariff 35% off', x: 68, y: 45, rating: 4.7 },
      { id: 'u3', name: 'Munnar Town Central Plaza', category: 'meeting', description: 'Group jeep safari rendezvous point', discountNote: 'TERRA VISTAS welcome counter', x: 45, y: 55, rating: 4.8 },
      { id: 'u4', name: 'Cloud Valley Plantation Stay', category: 'hotel', description: 'Eco cottages surrounded by cardamom', discountNote: 'Group booking ₹1,150/person', x: 55, y: 65, rating: 4.7 },
      { id: 'u5', name: 'Rapsy Malabar Spices Restaurant', category: 'restaurant', description: 'Authentic Kerala parotta & meals', discountNote: 'Group meal deal 20% off', x: 48, y: 52, rating: 4.6 },
    ],
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    tagline: 'Garden City & Startup Capital - Palaces, parks & craft brew',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    description: 'A dynamic cosmopolitan hub famous for lush colonial parks, Tudor-style palaces, India’s top craft breweries, and day treks around the granite Nandi Hills.',
    baseCost: 4000,
    bestTime: 'Year-round, best September to March',
    travelInfo: {
      nearestStation: 'KSR Bengaluru / Yesvantpur',
      nearestAirport: 'Kempegowda International (BLR)',
      localTransportModes: 'Namma Metro, AC Electric Vayu Vajra buses',
      weather: 'Pleasant 19°C – 28°C',
    },
    popularAttractions: [
      { name: 'Lalbagh Botanical Glass House', tag: 'Colonial Flora', description: 'Famous glass conservatory modeled on London Crystal Palace', estimatedSoloCost: 150, estimatedGroupCost: 80 },
      { name: 'Bangalore Tudor Palace', tag: 'Royal Architecture', description: 'Wodeyar dynasty royal estate with fortified towers and arches', estimatedSoloCost: 500, estimatedGroupCost: 320 },
      { name: 'Bannerghatta National Park Safari', tag: 'Biological Reserve', description: 'AC bus safari to spot royal Bengal tigers, lions and bear safari', estimatedSoloCost: 650, estimatedGroupCost: 420 },
      { name: 'Cubbon Park & Vidhana Soudha', tag: 'City Green Heart', description: '300-acre green lung beside grand neo-Dravidian state legislature', estimatedSoloCost: 100, estimatedGroupCost: 50 },
      { name: 'Nandi Hills Sunrise Excursion', tag: 'Clifftop Sunrise', description: 'Ancient hill fortress famous for sea of early morning clouds', estimatedSoloCost: 450, estimatedGroupCost: 260 },
    ],
    partnerOffersCount: 18,
    mapPoints: [
      { id: 'b1', name: 'Bangalore Palace Forecourt', category: 'attraction', description: 'Tudor style royal palace grounds', discountNote: 'Group audio-guide bundle', x: 45, y: 35, rating: 4.7 },
      { id: 'b2', name: 'Lalbagh West Gate', category: 'attraction', description: 'Botanical Glasshouse entrance', discountNote: 'Group nature walk pass', x: 50, y: 68, rating: 4.8 },
      { id: 'b3', name: 'MG Road Metro Exchange', category: 'meeting', description: 'Central urban transit pickup', discountNote: 'TERRA VISTAS group coach boarding', x: 55, y: 50, rating: 4.9 },
      { id: 'b4', name: 'The Chancery Pavilion', category: 'hotel', description: 'Deluxe business & leisure rooms', discountNote: 'Group package ₹1,200/person', x: 48, y: 55, rating: 4.6 },
      { id: 'b5', name: 'Vidyarthi Bhavan Heritage Meals', category: 'restaurant', description: 'Legendary crispy ghee masala dosa', discountNote: 'Pre-reserved group seating', x: 40, y: 72, rating: 4.9 },
    ],
  },
];

export const INITIAL_GROUPS: TravelGroup[] = [
  {
    id: 'araku-oct20-group',
    destinationId: 'araku-valley',
    destinationName: 'Araku Valley',
    destinationImage: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-10-20',
    returnDate: '2026-10-22',
    currentMembers: 18,
    maxMembers: 30,
    baseCost: 3800,
    estimatedGroupCost: 2600,
    potentialSavings: 1200,
    transportPreference: 'Shared AC Coach & Safari Jeeps',
    accommodationPreference: 'Valley Cottage Twin-sharing',
    budget: 'Economy to Moderate (₹2,500 – ₹3,000)',
    description: 'Scenic autumn expedition to Araku Valley! We will take the famous Vistadome train section, explore the illuminated Borra Caves, trek to Katiki waterfalls, and savor fresh organic coffee.',
    creatorName: 'Sai Kiran Rao',
    creatorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-01',
    verified: true,
    itineraryHighlights: [
      'Day 1: Scenic journey from Vizag, Check-in, Tribal Museum, Coffee Plantation stroll',
      'Day 2: Morning expedition to Borra Caves & Katiki Waterfall 4x4 Jeep Safari',
      'Day 3: Padmapuram Gardens, local Dhimsa dance cultural evening, departure',
    ],
    partnerOffersIncluded: [
      'Haritha Resort 30% group rate applied',
      'Shared Force Traveler transit discount',
      'Borra Caves fast-track group pass',
    ],
    members: [
      { id: 'u1', name: 'Sai Kiran Rao (Host)', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80', city: 'Visakhapatnam', joinedAt: '2026-10-01' },
      { id: 'u2', name: 'Priya Sharma', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80', city: 'Hyderabad', joinedAt: '2026-10-02' },
      { id: 'u3', name: 'Anish Varma', avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80', city: 'Bengaluru', joinedAt: '2026-10-03' },
      { id: 'u4', name: 'Deepa Nair', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80', city: 'Chennai', joinedAt: '2026-10-04' },
      { id: 'u5', name: 'Rohan Gupta', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80', city: 'Vijayawada', joinedAt: '2026-10-04' },
      { id: 'u6', name: 'Kavitha Reddy', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80', city: 'Hyderabad', joinedAt: '2026-10-05' },
    ],
  },
  {
    id: 'araku-oct22-group',
    destinationId: 'araku-valley',
    destinationName: 'Araku Valley',
    destinationImage: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-10-22',
    returnDate: '2026-10-24',
    currentMembers: 32,
    maxMembers: 40,
    baseCost: 3800,
    estimatedGroupCost: 2350,
    potentialSavings: 1450,
    transportPreference: 'Dedicated AC Luxury Bus',
    accommodationPreference: 'Eco Cottages & Camping',
    budget: 'Budget Saver (₹2,200 – ₹2,500)',
    description: 'High-volume community group heading to Araku Valley for a weekend retreat. With over 30 members already confirmed, our bulk partner discounts for transport and buffet meals are already active!',
    creatorName: 'Manoj Kumar',
    creatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-02',
    verified: true,
    itineraryHighlights: [
      'Day 1: AC coach departure, Chaparai cascade swimming, Campfire & BBQ',
      'Day 2: Borra Caves exploration, Coffee plantation walk, Tribal dance',
      'Day 3: Katiki falls adventure drive, souvenir shopping, return',
    ],
    partnerOffersIncluded: [
      'Max discount Tier 3 unlocked for stay',
      'Exclusive group buffet dining package',
      'Subsidized 4x4 Jeep fleet for Katiki',
    ],
    members: [
      { id: 'm1', name: 'Manoj Kumar (Host)', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80', city: 'Visakhapatnam', joinedAt: '2026-10-02' },
      { id: 'm2', name: 'Sneha Patel', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80', city: 'Surat', joinedAt: '2026-10-03' },
      { id: 'm3', name: 'Vikram Singh', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80', city: 'Bengaluru', joinedAt: '2026-10-03' },
    ],
  },
  {
    id: 'vizag-oct25-group',
    destinationId: 'visakhapatnam',
    destinationName: 'Visakhapatnam',
    destinationImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-10-25',
    returnDate: '2026-10-27',
    currentMembers: 14,
    maxMembers: 25,
    baseCost: 4200,
    estimatedGroupCost: 2980,
    potentialSavings: 1220,
    transportPreference: 'AC Mini-coach',
    accommodationPreference: 'Sea-facing Hotel',
    budget: 'Moderate (₹2,800 – ₹3,200)',
    description: 'Coastline exploration of Vizag with beach photography, submarine tour, and Kailasagiri ropeway ride. Join us for coastal dining and sea breeze.',
    creatorName: 'Arunav Roy',
    creatorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-03',
    verified: true,
    itineraryHighlights: [
      'Day 1: RK Beach, Submarine Museum, Coastal seafood dinner',
      'Day 2: Kailasagiri Ropeway, Yarada beach sunset excursion',
      'Day 3: Fishing harbor walk, Rushikonda beach watersports, departure',
    ],
    partnerOffersIncluded: ['Bay View Hotel 28% off', 'Submarine museum priority group entry'],
    members: [
      { id: 'v1', name: 'Arunav Roy (Host)', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80', city: 'Kolkata', joinedAt: '2026-10-03' },
    ],
  },
  {
    id: 'goa-nov05-group',
    destinationId: 'goa',
    destinationName: 'Goa',
    destinationImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-11-05',
    returnDate: '2026-11-09',
    currentMembers: 24,
    maxMembers: 35,
    baseCost: 5500,
    estimatedGroupCost: 3550,
    potentialSavings: 1950,
    transportPreference: 'Shared Mini Bus + Scuba Charter',
    accommodationPreference: 'Beachfront Cottages',
    budget: 'Value Package (₹3,400 – ₹3,800)',
    description: 'Post-monsoon sunny Goa vibes! Sharing transport across North and South Goa, private group boat to Grand Island for snorkeling, and evening shack gatherings.',
    creatorName: 'Neha Deshmukh',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-02',
    verified: true,
    itineraryHighlights: [
      'Day 1: Welcome sundowner at Vagator, group check-in',
      'Day 2: Grand Island private boat tour & snorkeling session',
      'Day 3: Old Goa churches, Fontainhas heritage Latin quarter stroll',
      'Day 4: Sunset cruise on Mandovi, beach shack bonfire',
    ],
    partnerOffersIncluded: ['Palm Grove Cottages 35% group deal', 'Private Boat charter split cost saving'],
    members: [
      { id: 'g1', name: 'Neha Deshmukh (Host)', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80', city: 'Mumbai', joinedAt: '2026-10-02' },
    ],
  },
  {
    id: 'ooty-oct18-group',
    destinationId: 'ooty',
    destinationName: 'Ooty',
    destinationImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-10-18',
    returnDate: '2026-10-21',
    currentMembers: 11,
    maxMembers: 20,
    baseCost: 4400,
    estimatedGroupCost: 3450,
    potentialSavings: 950,
    transportPreference: 'Shared Mountain Coach',
    accommodationPreference: 'Hilltop Pine Resort',
    budget: 'Economy (₹3,200 – ₹3,600)',
    description: 'Chilly morning walks through Nilgiri tea estates, Botanical Gardens flower exhibition, and vintage toy train ride through mountain tunnels.',
    creatorName: 'Karthik Raman',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-04',
    verified: true,
    itineraryHighlights: [
      'Day 1: Arrival & check-in, Botanical Gardens stroll, lake evening',
      'Day 2: Doddabetta Peak viewpoint, Pykara lake speedboat',
      'Day 3: Heritage Nilgiri steam train journey, chocolate factory',
    ],
    partnerOffersIncluded: ['Pine View Resort 25% off', 'Group boat pass on Ooty lake'],
    members: [
      { id: 'ot1', name: 'Karthik Raman (Host)', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80', city: 'Coimbatore', joinedAt: '2026-10-04' },
    ],
  },
  {
    id: 'munnar-nov12-group',
    destinationId: 'munnar',
    destinationName: 'Munnar',
    destinationImage: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-11-12',
    returnDate: '2026-11-15',
    currentMembers: 16,
    maxMembers: 30,
    baseCost: 4600,
    estimatedGroupCost: 3200,
    potentialSavings: 1400,
    transportPreference: 'Force Traveler & 4x4 Jeeps',
    accommodationPreference: 'Tea Plantation Estate',
    budget: 'Comfort (₹3,000 – ₹3,500)',
    description: 'Trek along tea-carpeted mountains, witness wild Nilgiri Tahrs at Eravikulam, and enjoy hot cardamom tea straight from the factory.',
    creatorName: 'Anand Thomas',
    creatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-03',
    verified: true,
    itineraryHighlights: [
      'Day 1: Tea factory visit, tea tasting, campfire evening',
      'Day 2: Eravikulam National park trek, Mattupetty dam boat cruise',
      'Day 3: Kundala lake, Attukal waterfalls, organic spice shopping',
    ],
    partnerOffersIncluded: ['Tea estate group stay discount', 'Shared Jeep safari split pricing'],
    members: [
      { id: 'mn1', name: 'Anand Thomas (Host)', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80', city: 'Kochi', joinedAt: '2026-10-03' },
    ],
  },
  {
    id: 'hyd-oct28-group',
    destinationId: 'hyderabad',
    destinationName: 'Hyderabad',
    destinationImage: 'https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-10-28',
    returnDate: '2026-10-30',
    currentMembers: 22,
    maxMembers: 30,
    baseCost: 3900,
    estimatedGroupCost: 2650,
    potentialSavings: 1250,
    transportPreference: 'AC Electric Tourist Bus',
    accommodationPreference: 'City Hotel',
    budget: 'Budget (₹2,500 – ₹2,900)',
    description: 'Heritage walks across Golconda Fort, Nizami food trails, Charminar night lights, and a full day exploring Ramoji Film City.',
    creatorName: 'Zainab Fatima',
    creatorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-04',
    verified: true,
    itineraryHighlights: [
      'Day 1: Charminar, Chowmahalla Palace, authentic Biryani food crawl',
      'Day 2: Ramoji Film City day pass with stunt shows',
      'Day 3: Golconda fort sound & light show, Hussain Sagar boat ride',
    ],
    partnerOffersIncluded: ['Ramoji bulk ticket discount 30%', 'Special Nizami banquet group deal'],
    members: [
      { id: 'h1', name: 'Zainab Fatima (Host)', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80', city: 'Hyderabad', joinedAt: '2026-10-04' },
    ],
  },
  {
    id: 'tirupati-nov02-group',
    destinationId: 'tirupati',
    destinationName: 'Tirupati',
    destinationImage: 'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-11-02',
    returnDate: '2026-11-04',
    currentMembers: 27,
    maxMembers: 35,
    baseCost: 3200,
    estimatedGroupCost: 2150,
    potentialSavings: 1050,
    transportPreference: 'Shared Pilgrim AC Coach',
    accommodationPreference: 'Pilgrim Guest Suites',
    budget: 'Pilgrim Saver (₹2,000 – ₹2,300)',
    description: 'Pilgrimage and sightseeing trip with shared uphill transport, Kapila Theertham visit, and Chandragiri Fort historical light show.',
    creatorName: 'Venkatachalam Murthy',
    creatorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    createdDate: '2026-10-03',
    verified: true,
    itineraryHighlights: [
      'Day 1: Alipiri assembly, check-in, Kapila Theertham',
      'Day 2: Tirumala temple coordination, Silathoranam natural arch',
      'Day 3: Chandragiri fort palace exploration, return journey',
    ],
    partnerOffersIncluded: ['Srinivasa Residency 35% group rate', 'Dedicated AC coach transfer'],
    members: [
      { id: 'tp1', name: 'Venkatachalam Murthy (Host)', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80', city: 'Nellore', joinedAt: '2026-10-03' },
    ],
  },
];

export const INITIAL_VENDOR_OFFERS: VendorOffer[] = [
  {
    id: 'vo-1',
    vendorId: 'v-haritha',
    vendorName: 'Haritha Valley Resort',
    category: 'Hotel',
    destination: 'Araku Valley',
    title: 'Deluxe Hill Cottages Group Offer',
    normalPrice: 1500,
    groupPrice: 1050,
    minGroupSize: 10,
    potentialSaving: 450,
    description: 'Spacious cottage twin-sharing with garden view, morning buffet breakfast, and complimentary campfire setup for groups of 10 or more.',
    active: true,
    validity: 'Valid till Nov 2026',
    badge: 'Popular Group Stay',
  },
  {
    id: 'vo-2',
    vendorId: 'v-tribaldining',
    vendorName: 'Araku Tribal Cuisine & Coffee',
    category: 'Restaurant',
    destination: 'Araku Valley',
    title: 'Traditional Bamboo Chicken & Thali Banquet',
    normalPrice: 800,
    groupPrice: 650,
    minGroupSize: 8,
    potentialSaving: 150,
    description: 'Signature organic tribal feast with fresh bamboo chicken, piping hot millet rotis, hill honey sweets, and fresh organic filter coffee.',
    active: true,
    validity: 'Valid year-round',
    badge: 'Foodie Choice',
  },
  {
    id: 'vo-3',
    vendorId: 'v-ghatstransport',
    vendorName: 'Eastern Ghats Travels & Safaris',
    category: 'Transport',
    destination: 'Araku Valley',
    title: '17-Seater AC Force Traveler & Katiki 4x4 Combo',
    normalPrice: 1000,
    groupPrice: 650,
    minGroupSize: 12,
    potentialSaving: 350,
    description: 'Door-to-door transport package from Vizag including mountain tolls, fuel, professional hill driver, and 4x4 jeep shuttle for Katiki waterfall.',
    active: true,
    validity: 'Valid till Dec 2026',
    badge: 'Top Rated Transport',
  },
  {
    id: 'vo-4',
    vendorId: 'v-borracaves',
    vendorName: 'Borra Speleo Tourism Board',
    category: 'Attraction',
    destination: 'Araku Valley',
    title: 'Fast-Track Group Entry & Certified Geologist Guide',
    normalPrice: 500,
    groupPrice: 350,
    minGroupSize: 15,
    potentialSaving: 150,
    description: 'Skip standard queues with fast-track entry barcode, certified local speleology guide, and audio headset commentary through limestone chambers.',
    active: true,
    validity: 'Valid all weekdays & weekends',
    badge: 'Fast Track Pass',
  },
  {
    id: 'vo-5',
    vendorId: 'v-coffeeestate',
    vendorName: 'Ananthagiri Organic Estate',
    category: 'Activity',
    destination: 'Araku Valley',
    title: 'Coffee Plantation Walking Tour & Roasting Class',
    normalPrice: 400,
    groupPrice: 250,
    minGroupSize: 10,
    potentialSaving: 150,
    description: 'Hands-on guided walk through arabica bushes, bean harvesting demonstration, live roasting workshop, and free take-home 100g sample pouch.',
    active: true,
    validity: 'Valid harvest season',
    badge: 'Experience',
  },
  {
    id: 'vo-6',
    vendorId: 'v-bayview',
    vendorName: 'Bay View Beachside Hotel',
    category: 'Hotel',
    destination: 'Visakhapatnam',
    title: 'Beachfront Deluxe Rooms with Breakfast',
    normalPrice: 1800,
    groupPrice: 1200,
    minGroupSize: 8,
    potentialSaving: 600,
    description: 'Overlooking RK Beach with private balcony, infinity pool access, and buffet breakfast included for group bookings.',
    active: true,
    validity: 'Valid till Nov 2026',
    badge: 'Sea View',
  },
  {
    id: 'vo-7',
    vendorId: 'v-palmgrove',
    vendorName: 'Palm Grove Beach Resort',
    category: 'Hotel',
    destination: 'Goa',
    title: 'Vagator Poolside Villa Group Package',
    normalPrice: 2200,
    groupPrice: 1450,
    minGroupSize: 12,
    potentialSaving: 750,
    description: 'Private 6-room villa cluster with shared pool, breakfast, and sunset cocktail pitcher included for verified TERRA VISTAS groups.',
    active: true,
    validity: 'Valid till Dec 2026',
    badge: 'Goa Favorite',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '5 more travelers joined your Araku group',
    description: 'Your Oct 20 group now has 18 travelers! Estimated price per person has decreased.',
    time: '15 mins ago',
    read: false,
    type: 'group_joined',
    linkTarget: { page: 'group-details', id: 'araku-oct20-group' },
  },
  {
    id: 'notif-2',
    title: 'Your estimated group cost decreased by ₹200',
    description: 'Bulk transport discount threshold was met. Group cost is now ₹2,600/person.',
    time: '1 hour ago',
    read: false,
    type: 'price_drop',
    linkTarget: { page: 'group-details', id: 'araku-oct20-group' },
  },
  {
    id: 'notif-3',
    title: 'A hotel partner added a 25% group offer',
    description: 'Haritha Valley Resort listed deluxe cottage packages for groups of 10+ travelers.',
    time: '3 hours ago',
    read: true,
    type: 'vendor_offer',
    linkTarget: { page: 'destination-details', id: 'araku-valley' },
  },
  {
    id: 'notif-4',
    title: 'Your group is 80% full',
    description: 'Araku Oct 22 group reached 32 of 40 travelers. Maximum savings tier is now unlocked!',
    time: 'Yesterday',
    read: true,
    type: 'capacity_alert',
    linkTarget: { page: 'group-details', id: 'araku-oct22-group' },
  },
  {
    id: 'notif-5',
    title: 'Smart Recommendation Available',
    description: '12 travelers are planning to visit Araku around your target date. Join to save up to ₹1,200!',
    time: '2 days ago',
    read: true,
    type: 'system',
    linkTarget: { page: 'planner' },
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'usr-current',
  name: 'Sai Sirisha',
  email: 'saisirisha@terravistas.in',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  role: 'traveler',
  phone: '+91 98490 12345',
  homeCity: 'Visakhapatnam, AP',
  bio: 'Explorer, nature lover & weekend trekker. Passionate about community group travels, mountain vistas, and cultural heritage.',
  travelStyle: 'Scenic Nature, Trekking & Cultural Heritage',
  joinedGroupsCount: 2,
  totalSaved: 2650,
  upcomingTripsCount: 1,
  badges: ['Verified Community Traveler', 'Early Explorer', 'Smart Saver Level 2', 'Eco Wanderer'],
};

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip-prev-1',
    groupId: 'vizag-oct25-group',
    destination: 'Visakhapatnam',
    destinationImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-10-25',
    returnDate: '2026-10-27',
    membersCount: 14,
    maxMembers: 25,
    estimatedPrice: 2980,
    potentialSavings: 1220,
    status: 'upcoming',
    bookedDate: '2026-10-04',
    bookingRef: 'TV-VZ-94021',
    transportMode: 'AC Mini-coach',
  },
  {
    id: 'trip-prev-0',
    groupId: 'ooty-oct18-group',
    destination: 'Ooty',
    destinationImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    travelDate: '2026-08-15',
    returnDate: '2026-08-18',
    membersCount: 18,
    maxMembers: 20,
    estimatedPrice: 3100,
    potentialSavings: 1300,
    status: 'completed',
    bookedDate: '2026-08-01',
    bookingRef: 'TV-OT-38910',
    transportMode: 'Mountain Coach',
  },
];
